services:
  esphome:
    image: ghcr.io/esphome/esphome:latest
    container_name: esphome
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Europe/Tallinn
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - esphome:/config
    labels:
      homepage.group: Docker
      homepage.name: ESPHome
      homepage.icon: esphome.png
      homepage.href: ${URL}
      homepage.widget.type: esphome
      homepage.widget.url: ${URL}
      homepage.widget.password: ${PASSWORD}
      homepage.widget.username: ${USERNAME}
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: 0.5

volumes:
  esphome:
    name: esphome
