services:
  esphome:
    image: ghcr.io/esphome/esphome
    container_name: esphome
    restart: unless-stopped
    network_mode: bridge
    environment:
      TZ: Europe/Tallinn
      ESPHOME_DASHBOARD_USE_PING: true
    ports:
      - 6052:6052
    volumes:
      - esphome:/config
    deploy:
      resources:
        limits:
          memory: 2.5G
          cpus: 0.25

volumes:
  esphome:
    name: esphome
