services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    restart: unless-stopped
    network_mode: bridge
    environment:
      TZ: Europe/Tallinn
    ports:
      - 80:8080
    volumes:
      - filebrowser:/.filebrowser.json
      - filebrowser_db:/database.db
      - /mnt:/srv
    user: ${UID}:${GID}
    labels:
      homepage.group: File Browser
      homepage.name: File Browser
      homepage.description: ${URL}
      homepage.icon: files.png
      homepage.href: ${URL}
    deploy:
      resources:
        limits:
          memory: 2.5G
          cpus: 0.25

volumes:
  filebrowser:
    name: filebrowser
  filebrowser_db:
    name: filebrowser_db
