services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    restart: unless-stopped
    network_mode: bridge
    cap_drop:
      - all
    environment:
      TZ: Europe/Tallinn
    ports:
      - 8080:80
    volumes:
      - /home/pi/filebrowser/filebrowser.json:/.filebrowser.json
      - /home/pi/filebrowser/database.db:/database.db
      - /mnt:/srv
    user: ${UID}:${GID}
    deploy:
      resources:
        limits:
          memory: 2.5G
          cpus: 0.25
