services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Europe/Tallinn
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/homeassistant:/config
      - /run/dbus:/run/dbus
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    deploy:
      resources:
        limits:
          memory: 2.5G
          cpus: 0.25
