services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:latest
    container_name: home-assistant
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Europe/Tallinn
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/homeassistant:/config
      - /run/dbus:/run/dbus
    devices:
      - /dev/serial/by-id/${ZIGBEE_TONGLE_ID}:/dev/ttyUSB0
    cap_add:
      - NET_ADMIN
      - NET_RAW
    deploy:
      resources:
        limits:
          memory: 2.5G
          cpus: 0.25
