services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Europe/Tallinn
    ports:
      - 3000:3000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - homepage:/app/config
    deploy:
      resources:
        limits:
          memory: 2.5G
          cpus: 0.25

volumes:
  homepage:
    name: homepage
