services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 5353:5353/udp
      - 8123:8123
      - 21063:21063
      - 51827:51827
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/homeassistant:/config
      - /run/dbus:/run/dbus
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    deploy:
      resources:
        limits:
          memory: 2560M
          cpus: 0.25
