services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:latest
    container_name: home-assistant
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Europe/Tallinn
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/homeassistant:/config
      - /run/dbus:/run/dbus
    devices:
      - /dev/serial/by-id/${ZIGBEE_TONGLE_ID}:/dev/ttyUSB0
    labels:
      homepage.group: Docker
      homepage.name: Home Assistant
      homepage.description: ${URL}
      homepage.icon: homeassistant.png
      homepage.href: ${URL}
      homepage.widget.type: homeassistant
      homepage.widget.url: ${URL}
      homepage.widget.key: ${TOKEN}
    deploy:
      resources:
        limits:
          memory: 2.5G
          cpus: 0.25
