services:
  music-assistant:
    image: ghcr.io/music-assistant/server:latest
    container_name: music-assistant
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Europe/Tallinn
    volumes:
      - music-assistant:/data
      # - ${USERDIR:-$HOME}/docker/music-assistant-server/data:/data/
    deploy:
      resources:
        limits:
          memory: 2.5G
          cpus: 0.25
    # privileged caps (and security-opt) needed to mount smb folders within the container
    # cap_add:
    #   - SYS_ADMIN
    #   - DAC_READ_SEARCH
    # security_opt:
    #   - apparmor:unconfined

volumes:
  music-assistant:
    name: music-assistant
