services:
  openthread:
    image: openthread/border-router:latest
    container_name: openthread
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Europe/Tallinn
      OT_RCP_DEVICE: "spinel+hdlc+uart:///dev/ttyUSB1?uart-baudrate=115200"
      OT_INFRA_IF: "eth0"
      OT_THREAD_IF: "wpan0"
      OT_LOG_LEVEL: "7"
      OT_REST_LISTEN_PORT: "8081"
      OT_REST_LISTEN_ADDR: "0.0.0.0"
    devices:
      - /dev/serial/by-id/${THREAD_TONGLE_ID}:/dev/ttyUSB1
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          memory: 2.5G
          cpus: 0.25
