services:
  openthread:
    image: openthread/otbr:latest
    container_name: openthread
    privileged: true
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Europe/Tallinn
      OTBR_DISABLE_FIREWALL: "1"
      OTBR_INFRA_IF_NAME: eth0
      OTBR_RADIO_URL: spinel+hdlc+uart:///dev/ttyUSB1
    volumes:
      - /home/pi/openthread:/var/lib/thread
    devices:
      - /dev/serial/by-id/${THREAD_TONGLE_ID}:/dev/ttyUSB1
    deploy:
      resources:
        limits:
          memory: 2.5G
          cpus: 0.25
