services:
  openthread:
    image: openthread/border-router:latest
    container_name: openthread
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    group_add:
      - 20
    environment:
      TZ: Europe/Tallinn
      OT_FORM_NETWORK: "1"
      OT_INFRA_IF: eth0
      OT_LOG_LEVEL: 7
      OT_RCP_DEVICE: "spinel+hdlc+uart:///dev/ttyUSB0?uart-baudrate=460800"
      OT_THREAD_IF: wpan0
      OTBR_ENABLE_TD_SERVER: "1"
    volumes:
      - /home/pi/openthread:/data
    devices:
      - /dev/serial/by-id/${THREAD_TONGLE_ID}:/dev/ttyUSB0
      - /dev/net/tun:/dev/net/tun
    deploy:
      resources:
        limits:
          memory: 2.5G
          cpus: 1.0

  openthread-web:
    image: alpine/socat:latest
    container_name: openthread-web
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Europe/Tallinn
    command: TCP-LISTEN:8090,fork,reuseaddr TCP:127.0.0.1:8080
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: 0.25
