services:
  openthread:
    image: openthread/otbr:latest
    container_name: openthread
    command: ["otbr-web", "-I", "wpan0", "-f"]
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Europe/Tallinn
      OTBR_DISABLE_BACKBONE_ROUTER: "1"
      OTBR_DISABLE_FIREWALL: "1"
      OTBR_RADIO_URL: spinel+hdlc+uart:///dev/ttyUSB0
    volumes:
      - /home/pi/openthread:/var/lib/thread
    devices:
      - /dev/serial/by-id/${THREAD_TONGLE_ID}:/dev/ttyUSB0
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
      - SYS_MODULE
    deploy:
      resources:
        limits:
          memory: 2.5G
          cpus: 0.25
