services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Europe/Tallinn
    volumes:
      - plex:/config
      - plex_transcode:/transcode
      - /mnt/ssd1:/data/ssd1
      - /mnt/ssd2:/data/ssd2
    labels:
      homepage.group: Docker
      homepage.name: Plex
      homepage.description: ${URL}/web
      homepage.icon: plex.png
      homepage.href: ${URL}/web
      homepage.widget.type: plex
      homepage.widget.url: ${URL}
      homepage.widget.key: ${TOKEN}
    deploy:
      resources:
        limits:
          memory: 2.5G
          cpus: 0.25

volumes:
  plex:
    name: plex
  plex_transcode:
    name: plex_transcode
