services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 1900:1900/udp
      - 32400:32400
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
      - 8324:8324
    volumes:
      - plex:/config
      - plex_transcode:/transcode
      - /mnt/ssd1:/data/ssd1
      - /mnt/ssd2:/data/ssd2
    deploy:
      resources:
        limits:
          memory: 2560M
          cpus: 0.25

volumes:
  plex:
    name: plex
  plex_transcode:
    name: plex_transcode
