services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    volumes:
      - plex:/config
      - plex_transcode:/transcode
      - /mnt/ssd1:/data/ssd1
      - /mnt/ssd2:/data/ssd2
    deploy:
      resources:
        limits:
          memory: 2560M
          cpus: 0.25

volumes:
  plex:
    name: plex
  plex_transcode:
    name: plex_transcode
