services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    network_mode: bridge
    environment:
      TZ: Europe/Tallinn
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    deploy:
      resources:
        limits:
          memory: 2.5G
          cpus: 0.25

volumes:
  portainer:
    name: portainer
