services:
  samba:
    image: ghcr.io/argoroots/samba:latest
    container_name: samba
    restart: unless-stopped
    network_mode: bridge
    environment:
      SAMBA_USER: ${SAMBA_USER}
      SAMBA_PASSWORD: ${SAMBA_PASSWORD}
    ports:
      - 445:445
    volumes:
      - /mnt:/shared
    labels:
      homepage.group: Docker
      homepage.name: Samba
      homepage.description: ${URL}
      homepage.icon: files.png
      homepage.href: ${URL}
    deploy:
      resources:
        limits:
          memory: 2.5G
          cpus: 0.25
