services:
  zigbee2mqtt:
    image: ghcr.io/koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Europe/Tallinn
    volumes:
      - /home/pi/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    devices:
      - /dev/serial/by-id/${ZIGBEE_TONGLE_ID}:/dev/ttyUSB0
