services:
  zigbee2mqtt:
    image: ghcr.io/koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Europe/Tallinn
      ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: 9123
    volumes:
      - /home/pi/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/serial/by-id/${ZIGBEE_TONGLE_ID}:/dev/ttyUSB0
    deploy:
      resources:
        limits:
          memory: 2.5G
          cpus: 0.25
