services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Europe/Tallinn

  zigbee2mqtt:
    image: ghcr.io/koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    restart: unless-stopped
    network_mode: host
    depends_on:
      - mosquitto
    environment:
      TZ: Europe/Tallinn
    volumes:
      - /home/pi/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/serial/by-id/${ZIGBEE_TONGLE_ID}:/dev/ttyUSB0
    deploy:
      resources:
        limits:
          memory: 2.5G
          cpus: 0.25
